matrix:
  include:
    - os: linux
      dist: xenial
      dotnet: 2.2
    - os: osx
      dotnet: 2.2.107
language: csharp
solution: QuestSaberPatch.sln
mono: none
dotnet: 2.2
script:
  - dotnet publish -c Release -r "${TRAVIS_OS_NAME}-x64" --self-contained true /p:useapphost=true
after_success:
  - cp ./jsonApp/bin/Release/netcoreapp2.2/${TRAVIS_OS_NAME}-x64/publish/jsonApp* ./app/bin/Release/netcoreapp2.2/${TRAVIS_OS_NAME}-x64/publish/
  - cd app/bin/Release/netcoreapp2.2/${TRAVIS_OS_NAME}-x64
  - mv publish questsaberpatch
  - ls -lAhR questsaberpatch
  - zip -r questsaberpatch.zip questsaberpatch
  - ls -lAhR
  - curl -F'file=@questsaberpatch.zip' https://0x0.st

